services:
  database:
    image: 'postgres:16.0-alpine3.18'
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    image: 'node:18-alpine'
    restart: always
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
    depends_on:
      - database
    command: sh -c "npm install && npm run dev"

  redis:
    image: 'redis:7.0-alpine'
    restart: always
    ports:
      - '6379:6379'

volumes:
  postgres_data:
    driver: local
